"""empty message

Revision ID: 02f2f31cbf39
Revises: 9ecc0d8782af
Create Date: 2025-11-07 22:27:17.385987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f2f31cbf39'
down_revision: Union[str, None] = '9ecc0d8782af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_payments', sa.Column('payment_card_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('card_for_auto_pay', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'card_for_auto_pay')
    op.drop_column('click_payments', 'payment_card_id')
    # ### end Alembic commands ###
