"""Update schuledi1

Revision ID: 32da4931c5ee
Revises: 984b8fd4a94b
Create Date: 2025-10-02 09:17:23.213709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32da4931c5ee'
down_revision: Union[str, None] = '984b8fd4a94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', sa.String(length=10), nullable=False))
    op.add_column('appointments', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.alter_column('appointments', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('appointments', 'service_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('appointments', 'service_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('appointments', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'is_cancelled')
    op.drop_column('appointments', 'is_completed')
    op.drop_column('appointments', 'is_confirmed')
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###
