"""scedule_books start_time end_time

Revision ID: 4ceed921d88b
Revises: 2a3b4c5d6e7f
Create Date: 2025-11-16 22:26:38.772347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceed921d88b'
down_revision: Union[str, None] = '2a3b4c5d6e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_books', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('schedule_books', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_books', 'end_time')
    op.drop_column('schedule_books', 'start_time')
    # ### end Alembic commands ###
