"""A message describing the model changes

Revision ID: 5c64d54205e2
Revises: 8b1c2d3e4f50
Create Date: 2025-12-22 22:16:43.295733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c64d54205e2'
down_revision: Union[str, None] = '8b1c2d3e4f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('whole_day', sa.Boolean(), nullable=True))
    op.add_column('schedules', sa.Column('service_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'service_duration')
    op.drop_column('schedules', 'whole_day')
    # ### end Alembic commands ###
