"""sync models (create missing tables)

Revision ID: 6d53b89e2a41
Revises: 8fcf18a988cf
Create Date: 2025-10-07 19:34:36.177343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d53b89e2a41'
down_revision: Union[str, None] = '8fcf18a988cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
