"""add column table admin avatar_url

Revision ID: 8fcf18a988cf
Revises: 2972a568f032
Create Date: 2025-10-07 17:17:11.307614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcf18a988cf'
down_revision: Union[str, None] = '2972a568f032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'avatar_url')
    # ### end Alembic commands ###
