"""Update SaloTOpHistory: add action

Revision ID: 90de1bfda8c2
Revises: 
Create Date: 2025-10-02 00:08:05.643398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90de1bfda8c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salon_top_history', sa.Column('action', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salon_top_history', 'action')
    # ### end Alembic commands ###
