"""Update schuledi

Revision ID: 984b8fd4a94b
Revises: 
Create Date: 2025-10-02 09:15:09.434953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '984b8fd4a94b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('application_number', sa.String(length=50), nullable=False))
    op.add_column('appointments', sa.Column('user_name', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('appointments', sa.Column('application_date', sa.Date(), nullable=False))
    op.add_column('appointments', sa.Column('application_time', sa.Time(), nullable=False))
    op.add_column('appointments', sa.Column('schedule_id', sa.UUID(), nullable=False))
    op.alter_column('appointments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('appointments', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('appointments', 'service_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.create_index(op.f('ix_appointments_application_number'), 'appointments', ['application_number'], unique=True)
    op.create_foreign_key(None, 'appointments', 'schedules', ['schedule_id'], ['id'])
    op.drop_column('appointments', 'appointment_date')
    op.drop_column('appointments', 'is_cancelled')
    op.drop_column('appointments', 'is_completed')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'is_confirmed')
    op.drop_column('appointments', 'appointment_time')
    op.add_column('employees', sa.Column('position', sa.String(length=100), nullable=True))
    op.alter_column('schedules', 'repeat_value',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'repeat_value',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('employees', 'position')
    op.add_column('appointments', sa.Column('appointment_time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('cancellation_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_application_number'), table_name='appointments')
    op.alter_column('appointments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('appointments', 'service_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('appointments', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('appointments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('appointments', 'schedule_id')
    op.drop_column('appointments', 'application_time')
    op.drop_column('appointments', 'application_date')
    op.drop_column('appointments', 'phone_number')
    op.drop_column('appointments', 'user_name')
    op.drop_column('appointments', 'application_number')
    # ### end Alembic commands ###
