"""empty message

Revision ID: 9ecc0d8782af
Revises: 58a96ab93c9b
Create Date: 2025-11-07 21:36:01.099794

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9ecc0d8782af'
down_revision: Union[str, None] = '58a96ab93c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'users' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('users')]
        if 'auto_pay_for_premium' not in columns:
            op.add_column('users', sa.Column('auto_pay_for_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'users' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('users')]
        if 'auto_pay_for_premium' in columns:
            op.drop_column('users', 'auto_pay_for_premium')

    # Create notifs table only if not exists
    if 'notifs' not in inspector.get_table_names():
        op.create_table('notifs',
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifs_ibfk_1'),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###
