"""Update appointment1

Revision ID: b14482a75830
Revises: 32da4931c5ee
Create Date: 2025-10-02 09:22:54.532611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14482a75830'
down_revision: Union[str, None] = '32da4931c5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_salon_id_fkey', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'salon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('salon_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('appointments_salon_id_fkey', 'appointments', 'salons', ['salon_id'], ['id'])
    # ### end Alembic commands ###
