"""resync models

Revision ID: b4d11c517264
Revises: c80410ad5666
Create Date: 2025-10-31 22:31:56.256365

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b4d11c517264'
down_revision: Union[str, None] = 'c80410ad5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    table_names = inspector.get_table_names()
    is_sqlite = conn.dialect.name == 'sqlite'

    # Foreign key constraint - skip for SQLite, check tables exist
    if not is_sqlite and 'appointments' in table_names and 'employees' in table_names:
        # Check if FK already exists
        fks = inspector.get_foreign_keys('appointments')
        has_employee_fk = any(fk.get('referred_table') == 'employees' for fk in fks)
        if not has_employee_fk:
            columns = [col['name'] for col in inspector.get_columns('appointments')]
            if 'employee_id' in columns:
                op.create_foreign_key(None, 'appointments', 'employees', ['employee_id'], ['id'])

    # payment_cards operations - only if table exists
    if 'payment_cards' in table_names:
        columns = [col['name'] for col in inspector.get_columns('payment_cards')]

        # Add new columns if they don't exist
        if 'card_token' not in columns:
            op.add_column('payment_cards', sa.Column('card_token', sa.String(length=255), nullable=True))
        if 'card_number' not in columns:
            op.add_column('payment_cards', sa.Column('card_number', sa.String(length=255), nullable=True))
        if 'expiry_at' not in columns:
            op.add_column('payment_cards', sa.Column('expiry_at', sa.Text(), nullable=True))
        if 'is_verified' not in columns:
            op.add_column('payment_cards', sa.Column('is_verified', sa.Boolean(), nullable=True))

        # These operations are not supported in SQLite
        if not is_sqlite:
            # Drop index only if it exists
            indexes = inspector.get_indexes('payment_cards')
            index_names = [idx['name'] for idx in indexes if idx.get('name')]
            if 'user_id' in index_names:
                op.drop_index('user_id', table_name='payment_cards')

            # Create unique constraint only if card_token column exists and constraint doesn't exist
            unique_constraints = inspector.get_unique_constraints('payment_cards')
            has_card_token_unique = any('card_token' in uc.get('column_names', []) for uc in unique_constraints)
            if not has_card_token_unique and 'card_token' in columns or 'card_token' not in columns:
                # Refresh columns after potential add
                columns = [col['name'] for col in inspector.get_columns('payment_cards')]
                if 'card_token' in columns:
                    op.create_unique_constraint('uq_payment_cards_card_token', 'payment_cards', ['card_token'])

            # Drop old columns
            for col in ['expiry_month', 'card_holder_name', 'phone_number', 'last_four_digits', 'expiry_year', 'card_type', 'card_number_encrypted']:
                if col in columns:
                    op.drop_column('payment_cards', col)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    table_names = inspector.get_table_names()
    is_sqlite = conn.dialect.name == 'sqlite'

    if 'payment_cards' in table_names:
        columns = [col['name'] for col in inspector.get_columns('payment_cards')]

        if not is_sqlite:
            # Add old columns back
            for col_name, col_type in [
                ('card_number_encrypted', sa.String(length=255)),
                ('card_type', sa.String(length=20)),
                ('expiry_year', sa.Integer()),
                ('last_four_digits', sa.String(length=4)),
                ('phone_number', sa.String(length=20)),
                ('card_holder_name', sa.String(length=100)),
                ('expiry_month', sa.Integer())
            ]:
                if col_name not in columns:
                    op.add_column('payment_cards', sa.Column(col_name, col_type, nullable=True))

            # Drop unique constraint if exists
            unique_constraints = inspector.get_unique_constraints('payment_cards')
            for uc in unique_constraints:
                if 'card_token' in uc.get('column_names', []):
                    op.drop_constraint(uc['name'], 'payment_cards', type_='unique')
                    break

            # Create index if not exists
            indexes = inspector.get_indexes('payment_cards')
            index_names = [idx['name'] for idx in indexes if idx.get('name')]
            if 'user_id' not in index_names:
                # Refresh columns
                columns = [col['name'] for col in inspector.get_columns('payment_cards')]
                if 'user_id' in columns and 'card_number_encrypted' in columns:
                    op.create_index('user_id', 'payment_cards', ['user_id', 'card_number_encrypted'], unique=True)

        # Drop new columns
        columns = [col['name'] for col in inspector.get_columns('payment_cards')]
        for col in ['is_verified', 'expiry_at', 'card_number', 'card_token']:
            if col in columns:
                op.drop_column('payment_cards', col)

    # Drop FK from appointments if exists
    if not is_sqlite and 'appointments' in table_names:
        fks = inspector.get_foreign_keys('appointments')
        for fk in fks:
            if fk.get('referred_table') == 'employees' and fk.get('name'):
                op.drop_constraint(fk['name'], 'appointments', type_='foreignkey')
                break
    # ### end Alembic commands ###
