"""resync models

Revision ID: b4d11c517264
Revises: c80410ad5666
Create Date: 2025-10-31 22:31:56.256365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4d11c517264'
down_revision: Union[str, None] = 'c80410ad5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointments', 'employees', ['employee_id'], ['id'])
    op.add_column('payment_cards', sa.Column('card_token', sa.String(length=255), nullable=False))
    op.add_column('payment_cards', sa.Column('card_number', sa.String(length=255), nullable=False))
    op.add_column('payment_cards', sa.Column('expiry_at', sa.Text(), nullable=False))
    op.add_column('payment_cards', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_index('user_id', table_name='payment_cards')
    op.create_unique_constraint(None, 'payment_cards', ['card_token'])
    op.drop_column('payment_cards', 'expiry_month')
    op.drop_column('payment_cards', 'card_holder_name')
    op.drop_column('payment_cards', 'phone_number')
    op.drop_column('payment_cards', 'last_four_digits')
    op.drop_column('payment_cards', 'expiry_year')
    op.drop_column('payment_cards', 'card_type')
    op.drop_column('payment_cards', 'card_number_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_cards', sa.Column('card_number_encrypted', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('payment_cards', sa.Column('card_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('payment_cards', sa.Column('expiry_year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('payment_cards', sa.Column('last_four_digits', mysql.VARCHAR(length=4), nullable=False))
    op.add_column('payment_cards', sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('payment_cards', sa.Column('card_holder_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('payment_cards', sa.Column('expiry_month', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment_cards', type_='unique')
    op.create_index('user_id', 'payment_cards', ['user_id', 'card_number_encrypted'], unique=True)
    op.drop_column('payment_cards', 'is_verified')
    op.drop_column('payment_cards', 'expiry_at')
    op.drop_column('payment_cards', 'card_number')
    op.drop_column('payment_cards', 'card_token')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # ### end Alembic commands ###
