"""resync models

Revision ID: b4d11c517264
Revises: c80410ad5666
Create Date: 2025-10-31 22:31:56.256365

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b4d11c517264'
down_revision: Union[str, None] = 'c80410ad5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    table_names = inspector.get_table_names()
    is_sqlite = conn.dialect.name == 'sqlite'

    # Foreign key constraint - skip for SQLite
    if not is_sqlite and 'appointments' in table_names:
        op.create_foreign_key(None, 'appointments', 'employees', ['employee_id'], ['id'])

    # payment_cards operations - only if table exists
    if 'payment_cards' in table_names:
        columns = [col['name'] for col in inspector.get_columns('payment_cards')]

        # Add new columns if they don't exist
        if 'card_token' not in columns:
            op.add_column('payment_cards', sa.Column('card_token', sa.String(length=255), nullable=True))
        if 'card_number' not in columns:
            op.add_column('payment_cards', sa.Column('card_number', sa.String(length=255), nullable=True))
        if 'expiry_at' not in columns:
            op.add_column('payment_cards', sa.Column('expiry_at', sa.Text(), nullable=True))
        if 'is_verified' not in columns:
            op.add_column('payment_cards', sa.Column('is_verified', sa.Boolean(), nullable=True))

        # These operations are not supported in SQLite
        if not is_sqlite:
            try:
                op.drop_index('user_id', table_name='payment_cards')
            except:
                pass
            op.create_unique_constraint(None, 'payment_cards', ['card_token'])

            # Drop old columns
            for col in ['expiry_month', 'card_holder_name', 'phone_number', 'last_four_digits', 'expiry_year', 'card_type', 'card_number_encrypted']:
                if col in columns:
                    op.drop_column('payment_cards', col)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    table_names = inspector.get_table_names()
    is_sqlite = conn.dialect.name == 'sqlite'

    if 'payment_cards' in table_names:
        columns = [col['name'] for col in inspector.get_columns('payment_cards')]

        if not is_sqlite:
            if 'card_number_encrypted' not in columns:
                op.add_column('payment_cards', sa.Column('card_number_encrypted', sa.String(length=255), nullable=True))
            if 'card_type' not in columns:
                op.add_column('payment_cards', sa.Column('card_type', sa.String(length=20), nullable=True))
            if 'expiry_year' not in columns:
                op.add_column('payment_cards', sa.Column('expiry_year', sa.Integer(), nullable=True))
            if 'last_four_digits' not in columns:
                op.add_column('payment_cards', sa.Column('last_four_digits', sa.String(length=4), nullable=True))
            if 'phone_number' not in columns:
                op.add_column('payment_cards', sa.Column('phone_number', sa.String(length=20), nullable=True))
            if 'card_holder_name' not in columns:
                op.add_column('payment_cards', sa.Column('card_holder_name', sa.String(length=100), nullable=True))
            if 'expiry_month' not in columns:
                op.add_column('payment_cards', sa.Column('expiry_month', sa.Integer(), nullable=True))

            try:
                op.drop_constraint(None, 'payment_cards', type_='unique')
            except:
                pass
            op.create_index('user_id', 'payment_cards', ['user_id', 'card_number_encrypted'], unique=True)

        for col in ['is_verified', 'expiry_at', 'card_number', 'card_token']:
            if col in columns:
                try:
                    op.drop_column('payment_cards', col)
                except:
                    pass

    if not is_sqlite and 'appointments' in table_names:
        try:
            op.drop_constraint(None, 'appointments', type_='foreignkey')
        except:
            pass
    # ### end Alembic commands ###
