"""empty message

Revision ID: c80410ad5666
Revises: 6d53b89e2a41
Create Date: 2025-10-19 11:24:45.364456

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c80410ad5666'
down_revision: Union[str, None] = '6d53b89e2a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifs')
    op.drop_constraint('appointments_ibfk_2', 'appointments', type_='foreignkey')
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('appointments')]
    if 'schedule_id' in columns:
        op.drop_column('appointments', 'schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('schedule_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key('appointments_ibfk_2', 'appointments', 'schedules', ['schedule_id'], ['id'])
    op.create_table('notifs',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
