"""empty message

Revision ID: c80410ad5666
Revises: 6d53b89e2a41
Create Date: 2025-10-19 11:24:45.364456

"""
from typing import Sequence, Union
from sqlalchemy import inspect
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c80410ad5666'
down_revision: Union[str, None] = '6d53b89e2a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    # Drop notifs table only if it exists
    if 'notifs' in inspector.get_table_names():
        op.drop_table('notifs')

    # Drop foreign key constraint only for MySQL (SQLite doesn't support this)
    if conn.dialect.name != 'sqlite':
        op.drop_constraint('appointments_ibfk_2', 'appointments', type_='foreignkey')

    columns = [col['name'] for col in inspector.get_columns('appointments')]
    if 'schedule_id' in columns:
        op.drop_column('appointments', 'schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)

    columns = [col['name'] for col in inspector.get_columns('appointments')]
    if 'schedule_id' not in columns:
        op.add_column('appointments', sa.Column('schedule_id', sa.String(length=36), nullable=True))

    if conn.dialect.name != 'sqlite':
        op.create_foreign_key('appointments_ibfk_2', 'appointments', 'schedules', ['schedule_id'], ['id'])

    if 'notifs' not in inspector.get_table_names():
        op.create_table('notifs',
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifs_ibfk_1'),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###
