"""Update appointment1

Revision ID: c8e406917347
Revises: b14482a75830
Create Date: 2025-10-02 09:25:26.277314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e406917347'
down_revision: Union[str, None] = 'b14482a75830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointment_time', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
