"""Update Salon

Revision ID: ca2d6e65fab6
Revises: 90de1bfda8c2
Create Date: 2025-10-02 03:06:44.537046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2d6e65fab6'
down_revision: Union[str, None] = '90de1bfda8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('orientation_uz', sa.Text(), nullable=True))
    op.add_column('salons', sa.Column('orientation_ru', sa.Text(), nullable=True))
    op.add_column('salons', sa.Column('orientation_en', sa.Text(), nullable=True))
    op.drop_column('salons', 'salon_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('salon_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('salons', 'orientation_en')
    op.drop_column('salons', 'orientation_ru')
    op.drop_column('salons', 'orientation_uz')
    # ### end Alembic commands ###
